"""initial schema

Revision ID: 471c9adcb2ad
Revises: 
Create Date: 2026-09-26

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '471c9adcb2ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ollama_model', sa.String(length=128), server_default='qwen2.5:3b-instruct-q4_K_M', nullable=False),
    sa.Column('num_thread', sa.Integer(), server_default='4', nullable=False),
    sa.Column('keep_alive', sa.String(length=16), server_default='2m', nullable=False),
    sa.Column('batch_interval_s', sa.Integer(), server_default='45', nullable=False),
    sa.Column('retention_days', sa.Integer(), server_default='14', nullable=False),
    sa.Column('about_me', sa.Text(), server_default='', nullable=False),
    sa.Column('backfill_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('batch_interval_s >= 10', name='ck_app_settings_batch_interval'),
    sa.CheckConstraint('id = 1', name='ck_app_settings_singleton'),
    sa.CheckConstraint('num_thread > 0', name='ck_app_settings_num_thread'),
    sa.CheckConstraint('retention_days > 0', name='ck_app_settings_retention'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discord_channels',
    sa.Column('channel_id', sa.String(length=32), nullable=False),
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('guild_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_index(op.f('ix_discord_channels_guild_id'), 'discord_channels', ['guild_id'], unique=False)
    op.create_table('listener_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('user_tag', sa.String(length=255), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('classifier_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('classifier_last_error', sa.Text(), nullable=True),
    sa.CheckConstraint('id = 1', name='ck_listener_status_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('guild_id', sa.String(length=32), nullable=True),
    sa.Column('channel_id', sa.String(length=32), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('criteria', sa.Text(), server_default='', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind <> 'channel' OR channel_id IS NOT NULL", name='ck_watches_channel_has_id'),
    sa.CheckConstraint("kind IN ('channel', 'all_dms', 'requests')", name='ck_watches_kind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('watch_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('discord_message_id', sa.String(length=32), nullable=True),
    sa.Column('guild_id', sa.String(length=32), nullable=True),
    sa.Column('guild_name', sa.String(length=255), nullable=True),
    sa.Column('channel_id', sa.String(length=32), nullable=True),
    sa.Column('channel_name', sa.String(length=255), nullable=True),
    sa.Column('author_id', sa.String(length=32), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('mentions_me', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reply_to_me', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_spam', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('jump_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('importance', sa.String(length=16), nullable=True),
    sa.Column('needs_reply', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("importance IS NULL OR importance IN ('ignore', 'fyi', 'important', 'urgent')", name='ck_items_importance'),
    sa.CheckConstraint("kind IN ('message', 'friend_request', 'message_request')", name='ck_items_kind'),
    sa.CheckConstraint("status IN ('pending', 'done', 'error')", name='ck_items_status'),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_message_id')
    )
    op.create_index('ix_items_channel_created', 'items', ['channel_id', 'created_at'], unique=False)
    op.create_index('ix_items_status_watch', 'items', ['status', 'watch_id'], unique=False)
    # ### end Alembic commands ###

    # The DM and request sections are singletons (the listener routes to "the"
    # all_dms/requests watch); a partial unique index enforces that in the DB.
    op.execute("CREATE UNIQUE INDEX uq_watches_builtin_kind ON watches (kind) WHERE kind <> 'channel'")

    op.execute("INSERT INTO app_settings (id) VALUES (1)")
    op.execute("INSERT INTO listener_status (id) VALUES (1)")
    watches = sa.table(
        'watches',
        sa.column('kind', sa.String),
        sa.column('label', sa.String),
        sa.column('criteria', sa.Text),
    )
    op.bulk_insert(watches, [
        {
            'kind': 'all_dms',
            'label': 'Direct messages',
            'criteria': (
                "Anything a friend asks me directly or is waiting on me for. "
                "Plans, invites and time-sensitive stuff are important. "
                "Casual banter, memes and link dumps are fyi at most."
            ),
        },
        {
            'kind': 'requests',
            'label': 'Friend & message requests',
            'criteria': (
                "Requests from people who share a server with me, or whose message is clearly personal and "
                "legitimate, are important. Obvious spam, scams, 'free nitro', crypto or trading offers are ignore."
            ),
        },
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS uq_watches_builtin_kind")
    op.drop_index('ix_items_status_watch', table_name='items')
    op.drop_index('ix_items_channel_created', table_name='items')
    op.drop_table('items')
    op.drop_table('watches')
    op.drop_table('listener_status')
    op.drop_index(op.f('ix_discord_channels_guild_id'), table_name='discord_channels')
    op.drop_table('discord_channels')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
